### ISSUE TITLE
Received empty message from server

### ISSUE THREAD

**Issue by towry** [leakec/multitask#8]
it outputs `Received empty message from server` and make current zellij session exit.

zellij 0.39.1

**Comment by leakec** [comment]
@towry We don't currently have the plugin compiled for `0.39.1`. In `0.39.*` I'm seeing two instances of the plugin being created, but have not gotten to the bottom of it yet (see #7). Once that is fixed, we'll release a `0.39` version which should work.

**Comment by leakec** [comment]
Just keeping this issue updated. @towry a recent commit was made on the `zellij` core that fixes the problem in #7. Whenever `zellij` makes another release I can publish a version of this plugin that will run without issue. Will keep this issue open until that happens.

**Comment by leakec** [comment]
@towry Okay, zellij 0.40.0 has released which fixed the issue! Just published a new version of the plugin. If you use that version of the plugin plus the new version of zellij you should be good to go.

**Comment by towry** [comment]
I am using zellij 0.41.0 build from source, just downloaded the wasm from release page, still have this issue.

**Comment by leakec** [comment]
@towry Just double checking you grabbed the wasm from the release page for `0.41.0` and not `0.41.1`, since `0.41.1` is the most recent. I think either likely work with `0.41.0`, since not much changed in the minor release, but would be worth double-checking and trying.

If you indeed have the `multitask` version that matches you `zellij` version, I want to check some other things quickly:
* Are you seeing a message requesting permissions for the plugin before this happens? If not, I'm curious if it's possible `zelllij` is using a cached version of the plugin which is older (and does not match the major version of `zellij` you have). If this is the case, may be worth clearing out the `zellij` cache folder.
* How are you trying to start the plugin? There are a few different commands to do this. Are you having a problem with all of them or just a particular one?
* If none of the above work, can you send me some information from the `zellij` log? Should be under `tmp` in a directory with a name like `zellij-1000`.

**Comment by towry** [comment]
@leakec Hi thanks for the reply. I am using zellij HEAD version which is 0.41.0 I think. and all the plugins is 0.40.1, like the vim-zellij-navigator have same issue. 

The version doesnt match.

I want to using the super key and modifier key which is available in HEAD only.

I am trying to fork those incompatible plugins and have some debugging to see if it works.

**Comment by leakec** [comment]
@towry Sounds good. Yeah, that makes sense. 

When I build against custom versions of `zellij` on my own machine all I need to do is change `Cargo.toml` to point to my local instance of `zellij-tile` and then running `cargo build` produces the `.wasm` file. 

Hope this works for you too. Please let me know if you run into any issues.
